package dev.maxblack.shortcutsensei.core.catalog

import dev.maxblack.shortcutsensei.core.model.ContextType
import dev.maxblack.shortcutsensei.core.model.Shortcut
import dev.maxblack.shortcutsensei.core.model.ShortcutCategory

/**
 * Master catalogue of IntelliJ IDEA shortcuts with rich metadata.
 *
 * ── Design principles ──────────────────────────────────────────────────────────
 * 1. Key bindings are NOT stored here. They are always read at runtime from the
 *    active keymap, ensuring Mac / Linux / Windows / Chrome OS all get the right keys.
 * 2. [Shortcut.popularityRank] is derived from JetBrains developer surveys, the
 *    IntelliJ Productivity Guide built into the IDE, and community rankings.
 *    Lower number = used more often.
 * 3. [Shortcut.canDemonstrate] = false means we cannot set up a meaningful live
 *    demo. These shortcuts are documented with [Shortcut.demonstrationNote] so the
 *    user still understands WHY they cannot be practised interactively.
 * 4. Grouped shortcuts share a [Shortcut.groupId] and are practised back-to-back.
 *
 * ── Shortcut coverage ─────────────────────────────────────────────────────────
 * This file covers the most important ~100 shortcuts. Additional shortcuts can be
 * added by creating new [Shortcut] entries in [ALL]. The engine picks them up
 * automatically on next plugin start.
 */
object BuiltinShortcutDefinitions {

    // ── Group definitions ─────────────────────────────────────────────────────

    data class GroupDef(
        val id: String,
        val displayName: String,
        val description: String,
        val shortcutIds: List<String>,
    )

    val GROUP_DEFS: List<GroupDef> = listOf(
        GroupDef(
            id = "extend-shrink-selection",
            displayName = "Extend / Shrink Selection",
            description = "Progressively grow the selection word → line → statement, then shrink it back.",
            shortcutIds = listOf(
                "extend-selection-1", "extend-selection-2", "extend-selection-3",
                "shrink-selection-1", "shrink-selection-2",
            ),
        ),
        GroupDef(
            id = "complete-statement-variants",
            displayName = "Statement Completion Variants",
            description = "Smart statement completion in three different code contexts: semicolon, close-paren, return.",
            shortcutIds = listOf(
                "complete-statement-semicolon",
                "complete-statement-paren",
                "complete-statement-return",
            ),
        ),
        GroupDef(
            id = "multi-caret",
            displayName = "Multiple Carets",
            description = "Add carets above / below, select next occurrence, then select all occurrences.",
            shortcutIds = listOf(
                "clone-caret-below", "clone-caret-above",
                "add-selection-next-occurrence", "select-all-occurrences",
            ),
        ),
        GroupDef(
            id = "live-rename",
            displayName = "Rename & Navigate Usages",
            description = "Rename a symbol, then jump forward and backward through its usages.",
            shortcutIds = listOf(
                "refactoring-rename", "find-next", "find-prev",
            ),
        ),
        GroupDef(
            id = "navigate-errors",
            displayName = "Navigate & Describe Errors",
            description = "Jump to the next error, then the previous one, then reveal the error tooltip.",
            shortcutIds = listOf(
                "goto-next-error", "goto-prev-error", "show-error-description",
            ),
        ),
        GroupDef(
            id = "code-folding",
            displayName = "Code Folding",
            description = "Collapse a block, expand it, collapse all, expand all.",
            shortcutIds = listOf(
                "collapse-block", "expand-block", "collapse-all", "expand-all",
            ),
        ),
        GroupDef(
            id = "extract-refactorings",
            displayName = "Extract Refactorings",
            description = "Extract variable, then method, from the same selection.",
            shortcutIds = listOf(
                "extract-variable", "extract-method",
            ),
        ),
    )

    // ── Shortcut list ─────────────────────────────────────────────────────────

    val ALL: List<Shortcut> = listOf(

        // ════════════════════════════════════════════════════════════════════
        // CODE COMPLETION
        // ════════════════════════════════════════════════════════════════════

        Shortcut(
            id = "basic-completion",
            actionId = "CodeCompletion",
            displayName = "Basic Code Completion",
            description = "Displays a list of basic code completion suggestions based on the context at the caret.",
            category = ShortcutCategory.CODE_COMPLETION,
            popularityRank = 1,
            contextType = ContextType.EDITOR_JAVA,
        ),
        Shortcut(
            id = "smart-completion",
            actionId = "SmartTypeCompletion",
            displayName = "Smart Type Completion",
            description = "Filters completion suggestions to types that match the expected type at the caret.",
            category = ShortcutCategory.CODE_COMPLETION,
            popularityRank = 5,
            contextType = ContextType.EDITOR_JAVA,
        ),
        Shortcut(
            id = "complete-statement-semicolon",
            actionId = "EditorCompleteStatement",
            displayName = "Complete Statement → add semicolon",
            description = "Completes the current statement and places a semicolon at the end of the line.",
            category = ShortcutCategory.CODE_COMPLETION,
            popularityRank = 8,
            contextType = ContextType.EDITOR_JAVA,
            groupId = "complete-statement-variants",
            groupPosition = 0,
            codeCompletionVariant = "SEMICOLON",
        ),
        Shortcut(
            id = "complete-statement-paren",
            actionId = "EditorCompleteStatement",
            displayName = "Complete Statement → close parenthesis",
            description = "Completes the current statement by inserting the closing parenthesis and semicolon.",
            category = ShortcutCategory.CODE_COMPLETION,
            popularityRank = 9,
            contextType = ContextType.EDITOR_JAVA,
            groupId = "complete-statement-variants",
            groupPosition = 1,
            codeCompletionVariant = "PARENTHESIS",
        ),
        Shortcut(
            id = "complete-statement-return",
            actionId = "EditorCompleteStatement",
            displayName = "Complete Statement → insert return expression",
            description = "Completes the current statement inside a return context, inserting the return keyword and braces.",
            category = ShortcutCategory.CODE_COMPLETION,
            popularityRank = 10,
            contextType = ContextType.EDITOR_JAVA,
            groupId = "complete-statement-variants",
            groupPosition = 2,
            codeCompletionVariant = "RETURN",
        ),
        Shortcut(
            id = "cyclic-expand-word",
            actionId = "HippieCompletion",
            displayName = "Hippie Completion (expand word)",
            description = "Cycles through possible word completions using words already present in the file.",
            category = ShortcutCategory.CODE_COMPLETION,
            popularityRank = 55,
            contextType = ContextType.EDITOR_ANY_CODE,
        ),
        Shortcut(
            id = "postfix-completion",
            actionId = "EditorChooseLookupItem",
            displayName = "Apply Live Template / Postfix Completion",
            description = "Applies a postfix template (e.g. type .if, .for, .null and press Tab to expand).",
            category = ShortcutCategory.LIVE_TEMPLATES,
            popularityRank = 48,
            contextType = ContextType.EDITOR_JAVA,
        ),

        // ════════════════════════════════════════════════════════════════════
        // NAVIGATION
        // ════════════════════════════════════════════════════════════════════

        Shortcut(
            id = "goto-class",
            actionId = "GotoClass",
            displayName = "Go to Class",
            description = "Opens a search dialog to jump to any class by name (fuzzy search supported).",
            category = ShortcutCategory.NAVIGATION,
            popularityRank = 2,
            contextType = ContextType.ANY,
        ),
        Shortcut(
            id = "goto-file",
            actionId = "GotoFile",
            displayName = "Go to File",
            description = "Opens a search dialog to navigate to any file in the project by name.",
            category = ShortcutCategory.NAVIGATION,
            popularityRank = 3,
            contextType = ContextType.ANY,
        ),
        Shortcut(
            id = "goto-symbol",
            actionId = "GotoSymbol",
            displayName = "Go to Symbol",
            description = "Searches for any symbol (method, field, variable) across the entire project.",
            category = ShortcutCategory.NAVIGATION,
            popularityRank = 4,
            contextType = ContextType.ANY,
        ),
        Shortcut(
            id = "goto-declaration",
            actionId = "GotoDeclaration",
            displayName = "Go to Declaration or Usages",
            description = "Navigates to the declaration of the element under the caret. If already on a declaration, shows usages.",
            category = ShortcutCategory.NAVIGATION,
            popularityRank = 6,
            contextType = ContextType.EDITOR_JAVA,
        ),
        Shortcut(
            id = "goto-implementation",
            actionId = "GotoImplementation",
            displayName = "Go to Implementation(s)",
            description = "Shows all concrete implementations of the interface or abstract method under the caret.",
            category = ShortcutCategory.NAVIGATION,
            popularityRank = 12,
            contextType = ContextType.EDITOR_JAVA,
        ),
        Shortcut(
            id = "goto-super",
            actionId = "GotoSuperMethod",
            displayName = "Go to Super Method / Class",
            description = "Navigates to the super class or the method in the parent class that the current one overrides.",
            category = ShortcutCategory.NAVIGATION,
            popularityRank = 30,
            contextType = ContextType.EDITOR_JAVA,
        ),
        Shortcut(
            id = "goto-test",
            actionId = "GotoTest",
            displayName = "Go to Test",
            description = "Navigates from a class to its test class, or creates one if none exists.",
            category = ShortcutCategory.NAVIGATION,
            popularityRank = 35,
            contextType = ContextType.EDITOR_JAVA,
        ),
        Shortcut(
            id = "back",
            actionId = "Back",
            displayName = "Navigate Back",
            description = "Returns to the previous cursor location in the navigation history.",
            category = ShortcutCategory.NAVIGATION,
            popularityRank = 15,
            contextType = ContextType.ANY,
        ),
        Shortcut(
            id = "forward",
            actionId = "Forward",
            displayName = "Navigate Forward",
            description = "Moves forward in the navigation history after navigating back.",
            category = ShortcutCategory.NAVIGATION,
            popularityRank = 16,
            contextType = ContextType.ANY,
        ),
        Shortcut(
            id = "find-usages",
            actionId = "FindUsages",
            displayName = "Find Usages",
            description = "Finds and lists all places in the project where the symbol under the caret is used.",
            category = ShortcutCategory.NAVIGATION,
            popularityRank = 7,
            contextType = ContextType.EDITOR_JAVA,
        ),
        Shortcut(
            id = "find-next",
            actionId = "FindNext",
            displayName = "Find Next Occurrence",
            description = "Jumps to the next occurrence of the current search term.",
            category = ShortcutCategory.NAVIGATION,
            popularityRank = 20,
            contextType = ContextType.EDITOR_ANY_CODE,
            groupId = "live-rename",
            groupPosition = 1,
        ),
        Shortcut(
            id = "find-prev",
            actionId = "FindPrevious",
            displayName = "Find Previous Occurrence",
            description = "Jumps to the previous occurrence of the current search term.",
            category = ShortcutCategory.NAVIGATION,
            popularityRank = 21,
            contextType = ContextType.EDITOR_ANY_CODE,
            groupId = "live-rename",
            groupPosition = 2,
        ),
        Shortcut(
            id = "goto-next-error",
            actionId = "GotoNextError",
            displayName = "Navigate to Next Error / Warning",
            description = "Moves the caret to the next error or warning marker in the current file.",
            category = ShortcutCategory.NAVIGATION,
            popularityRank = 25,
            contextType = ContextType.EDITOR_WITH_ERRORS,
            groupId = "navigate-errors",
            groupPosition = 0,
        ),
        Shortcut(
            id = "goto-prev-error",
            actionId = "GotoPreviousError",
            displayName = "Navigate to Previous Error / Warning",
            description = "Moves the caret to the previous error or warning marker in the current file.",
            category = ShortcutCategory.NAVIGATION,
            popularityRank = 26,
            contextType = ContextType.EDITOR_WITH_ERRORS,
            groupId = "navigate-errors",
            groupPosition = 1,
        ),
        Shortcut(
            id = "show-error-description",
            actionId = "ShowErrorDescription",
            displayName = "Show Error Description",
            description = "Displays the full error or warning tooltip at the caret position.",
            category = ShortcutCategory.NAVIGATION,
            popularityRank = 27,
            contextType = ContextType.EDITOR_WITH_ERRORS,
            groupId = "navigate-errors",
            groupPosition = 2,
        ),
        Shortcut(
            id = "recent-files",
            actionId = "RecentFiles",
            displayName = "Recent Files",
            description = "Shows a popup of recently opened files for quick switching.",
            category = ShortcutCategory.NAVIGATION,
            popularityRank = 14,
            contextType = ContextType.ANY,
        ),
        Shortcut(
            id = "recent-locations",
            actionId = "RecentLocations",
            displayName = "Recent Locations",
            description = "Shows a popup of recent cursor locations in the editor with code previews.",
            category = ShortcutCategory.NAVIGATION,
            popularityRank = 22,
            contextType = ContextType.ANY,
        ),
        Shortcut(
            id = "switcher",
            actionId = "Switcher",
            displayName = "Switcher",
            description = "Opens a popup to quickly switch between open editor tabs and tool windows.",
            category = ShortcutCategory.NAVIGATION,
            popularityRank = 18,
            contextType = ContextType.ANY,
        ),
        Shortcut(
            id = "goto-line",
            actionId = "GotoLine",
            displayName = "Go to Line / Column",
            description = "Opens a dialog to jump directly to a specific line and column number.",
            category = ShortcutCategory.NAVIGATION,
            popularityRank = 32,
            contextType = ContextType.EDITOR_ANY_CODE,
        ),
        Shortcut(
            id = "file-structure",
            actionId = "FileStructurePopup",
            displayName = "File Structure",
            description = "Shows an in-file structure popup (methods, fields, inner classes) for quick navigation.",
            category = ShortcutCategory.NAVIGATION,
            popularityRank = 19,
            contextType = ContextType.EDITOR_JAVA,
        ),
        Shortcut(
            id = "select-in",
            actionId = "SelectIn",
            displayName = "Select In…",
            description = "Selects the current file in the Project tree, Favorites, or other tool windows.",
            category = ShortcutCategory.NAVIGATION,
            popularityRank = 38,
            contextType = ContextType.EDITOR_ANY_CODE,
        ),

        // ════════════════════════════════════════════════════════════════════
        // EDITING
        // ════════════════════════════════════════════════════════════════════

        Shortcut(
            id = "extend-selection-1",
            actionId = "EditorSelectWord",
            displayName = "Extend Selection (to word)",
            description = "Extends the current selection to encompass the word at the caret.",
            category = ShortcutCategory.EDITING,
            popularityRank = 11,
            contextType = ContextType.EDITOR_ANY_CODE,
            groupId = "extend-shrink-selection",
            groupPosition = 0,
        ),
        Shortcut(
            id = "extend-selection-2",
            actionId = "EditorSelectWord",
            displayName = "Extend Selection (to expression)",
            description = "Continues extending the selection to encompass the full expression.",
            category = ShortcutCategory.EDITING,
            popularityRank = 11,
            contextType = ContextType.EDITOR_ANY_CODE,
            groupId = "extend-shrink-selection",
            groupPosition = 1,
        ),
        Shortcut(
            id = "extend-selection-3",
            actionId = "EditorSelectWord",
            displayName = "Extend Selection (to statement / block)",
            description = "Continues extending the selection to encompass the entire statement or block.",
            category = ShortcutCategory.EDITING,
            popularityRank = 11,
            contextType = ContextType.EDITOR_ANY_CODE,
            groupId = "extend-shrink-selection",
            groupPosition = 2,
        ),
        Shortcut(
            id = "shrink-selection-1",
            actionId = "EditorUnSelectWord",
            displayName = "Shrink Selection (one level)",
            description = "Shrinks the selection back by one structural level.",
            category = ShortcutCategory.EDITING,
            popularityRank = 13,
            contextType = ContextType.EDITOR_WITH_SELECTION,
            groupId = "extend-shrink-selection",
            groupPosition = 3,
        ),
        Shortcut(
            id = "shrink-selection-2",
            actionId = "EditorUnSelectWord",
            displayName = "Shrink Selection (back to word)",
            description = "Shrinks the selection back to just the word level.",
            category = ShortcutCategory.EDITING,
            popularityRank = 13,
            contextType = ContextType.EDITOR_WITH_SELECTION,
            groupId = "extend-shrink-selection",
            groupPosition = 4,
        ),
        Shortcut(
            id = "duplicate-line",
            actionId = "EditorDuplicate",
            displayName = "Duplicate Line or Selection",
            description = "Duplicates the current line or the selected block directly below.",
            category = ShortcutCategory.EDITING,
            popularityRank = 17,
            contextType = ContextType.EDITOR_ANY_CODE,
        ),
        Shortcut(
            id = "delete-line",
            actionId = "EditorDeleteLine",
            displayName = "Delete Line",
            description = "Deletes the entire line at the caret without leaving a blank line.",
            category = ShortcutCategory.EDITING,
            popularityRank = 19,
            contextType = ContextType.EDITOR_ANY_CODE,
        ),
        Shortcut(
            id = "move-line-up",
            actionId = "MoveLineUp",
            displayName = "Move Statement Up",
            description = "Moves the current line or statement upward, reordering code structurally.",
            category = ShortcutCategory.EDITING,
            popularityRank = 23,
            contextType = ContextType.EDITOR_ANY_CODE,
        ),
        Shortcut(
            id = "move-line-down",
            actionId = "MoveLineDown",
            displayName = "Move Statement Down",
            description = "Moves the current line or statement downward, reordering code structurally.",
            category = ShortcutCategory.EDITING,
            popularityRank = 24,
            contextType = ContextType.EDITOR_ANY_CODE,
        ),
        Shortcut(
            id = "comment-line",
            actionId = "CommentByLineComment",
            displayName = "Comment / Uncomment Line",
            description = "Toggles a single-line comment on the current line or all selected lines.",
            category = ShortcutCategory.EDITING,
            popularityRank = 28,
            contextType = ContextType.EDITOR_ANY_CODE,
        ),
        Shortcut(
            id = "comment-block",
            actionId = "CommentByBlockComment",
            displayName = "Comment / Uncomment Block",
            description = "Wraps the selected code in a block comment, or removes an existing block comment.",
            category = ShortcutCategory.EDITING,
            popularityRank = 33,
            contextType = ContextType.EDITOR_WITH_SELECTION,
        ),
        Shortcut(
            id = "reformat-code",
            actionId = "ReformatCode",
            displayName = "Reformat Code",
            description = "Reformats the current file or selection according to the project's code style settings.",
            category = ShortcutCategory.EDITING,
            popularityRank = 29,
            contextType = ContextType.EDITOR_ANY_CODE,
        ),
        Shortcut(
            id = "optimize-imports",
            actionId = "OptimizeImports",
            displayName = "Optimize Imports",
            description = "Removes unused import statements and re-orders the remaining ones.",
            category = ShortcutCategory.EDITING,
            popularityRank = 34,
            contextType = ContextType.EDITOR_JAVA,
        ),
        Shortcut(
            id = "show-intention-actions",
            actionId = "ShowIntentionActions",
            displayName = "Show Intention Actions / Quick Fix",
            description = "Opens the light-bulb menu with available quick fixes and intention actions at the caret.",
            category = ShortcutCategory.EDITING,
            popularityRank = 31,
            contextType = ContextType.EDITOR_WITH_ERRORS,
        ),
        Shortcut(
            id = "surround-with",
            actionId = "SurroundWith",
            displayName = "Surround With…",
            description = "Wraps the selected code with a construct: if, try/catch, for, synchronized, or a live template.",
            category = ShortcutCategory.EDITING,
            popularityRank = 36,
            contextType = ContextType.EDITOR_WITH_SELECTION,
        ),
        Shortcut(
            id = "unwrap-remove",
            actionId = "Unwrap",
            displayName = "Unwrap / Remove",
            description = "Removes a surrounding block (if, try, for) while preserving the inner code.",
            category = ShortcutCategory.EDITING,
            popularityRank = 44,
            contextType = ContextType.EDITOR_JAVA,
        ),
        Shortcut(
            id = "generate",
            actionId = "Generate",
            displayName = "Generate Code…",
            description = "Opens the Generate menu to insert constructors, getters/setters, toString, equals/hashCode, or overrides.",
            category = ShortcutCategory.EDITING,
            popularityRank = 37,
            contextType = ContextType.EDITOR_JAVA,
        ),
        Shortcut(
            id = "override-methods",
            actionId = "OverrideMethods",
            displayName = "Override Methods",
            description = "Shows methods from parent classes/interfaces that can be overridden in the current class.",
            category = ShortcutCategory.EDITING,
            popularityRank = 39,
            contextType = ContextType.EDITOR_JAVA,
        ),
        Shortcut(
            id = "implement-methods",
            actionId = "ImplementMethods",
            displayName = "Implement Methods",
            description = "Shows abstract/interface methods that must be implemented by the current class.",
            category = ShortcutCategory.EDITING,
            popularityRank = 40,
            contextType = ContextType.EDITOR_JAVA,
        ),
        Shortcut(
            id = "join-lines",
            actionId = "EditorJoinLines",
            displayName = "Join Lines",
            description = "Joins the next line to the current one, removing the line break and adjusting whitespace.",
            category = ShortcutCategory.EDITING,
            popularityRank = 50,
            contextType = ContextType.EDITOR_ANY_CODE,
        ),
        Shortcut(
            id = "toggle-case",
            actionId = "EditorToggleCase",
            displayName = "Toggle Case",
            description = "Toggles the selected text between UPPER CASE, lower case, and Title Case.",
            category = ShortcutCategory.EDITING,
            popularityRank = 60,
            contextType = ContextType.EDITOR_WITH_SELECTION,
        ),
        Shortcut(
            id = "parameter-info",
            actionId = "ParameterInfo",
            displayName = "Parameter Info",
            description = "Shows the parameter list for the method call at the caret — useful when inside parentheses.",
            category = ShortcutCategory.EDITING,
            popularityRank = 42,
            contextType = ContextType.EDITOR_JAVA,
        ),
        Shortcut(
            id = "quick-documentation",
            actionId = "QuickJavaDoc",
            displayName = "Quick Documentation",
            description = "Shows the inline documentation popup for the element under the caret.",
            category = ShortcutCategory.EDITING,
            popularityRank = 43,
            contextType = ContextType.EDITOR_JAVA,
        ),
        Shortcut(
            id = "quick-definition",
            actionId = "QuickImplementations",
            displayName = "Quick Definition",
            description = "Shows a pop-up preview of the definition of the symbol under the caret without navigating away.",
            category = ShortcutCategory.EDITING,
            popularityRank = 45,
            contextType = ContextType.EDITOR_JAVA,
        ),

        // ════════════════════════════════════════════════════════════════════
        // MULTIPLE CARETS
        // ════════════════════════════════════════════════════════════════════

        Shortcut(
            id = "clone-caret-below",
            actionId = "EditorCloneCaretBelow",
            displayName = "Add Caret Below",
            description = "Adds a second caret on the line below the current one, enabling simultaneous editing.",
            category = ShortcutCategory.MULTIPLE_CURSORS,
            popularityRank = 46,
            contextType = ContextType.EDITOR_ANY_CODE,
            groupId = "multi-caret",
            groupPosition = 0,
        ),
        Shortcut(
            id = "clone-caret-above",
            actionId = "EditorCloneCaretAbove",
            displayName = "Add Caret Above",
            description = "Adds a second caret on the line above the current one.",
            category = ShortcutCategory.MULTIPLE_CURSORS,
            popularityRank = 47,
            contextType = ContextType.EDITOR_ANY_CODE,
            groupId = "multi-caret",
            groupPosition = 1,
        ),
        Shortcut(
            id = "add-selection-next-occurrence",
            actionId = "SelectNextOccurrence",
            displayName = "Select Next Occurrence",
            description = "Adds the next occurrence of the selected text to the selection (multi-cursor select).",
            category = ShortcutCategory.MULTIPLE_CURSORS,
            popularityRank = 49,
            contextType = ContextType.EDITOR_ANY_CODE,
            groupId = "multi-caret",
            groupPosition = 2,
        ),
        Shortcut(
            id = "select-all-occurrences",
            actionId = "SelectAllOccurrences",
            displayName = "Select All Occurrences",
            description = "Selects every occurrence of the current word or selection in the file simultaneously.",
            category = ShortcutCategory.MULTIPLE_CURSORS,
            popularityRank = 51,
            contextType = ContextType.EDITOR_ANY_CODE,
            groupId = "multi-caret",
            groupPosition = 3,
        ),

        // ════════════════════════════════════════════════════════════════════
        // REFACTORING
        // ════════════════════════════════════════════════════════════════════

        Shortcut(
            id = "refactoring-rename",
            actionId = "RenameElement",
            displayName = "Rename",
            description = "Renames the symbol at the caret and automatically updates all its usages throughout the project.",
            category = ShortcutCategory.REFACTORING,
            popularityRank = 52,
            contextType = ContextType.EDITOR_JAVA,
            groupId = "live-rename",
            groupPosition = 0,
        ),
        Shortcut(
            id = "extract-variable",
            actionId = "IntroduceVariable",
            displayName = "Extract Variable",
            description = "Extracts the selected expression into a new local variable and replaces all occurrences.",
            category = ShortcutCategory.REFACTORING,
            popularityRank = 53,
            contextType = ContextType.EDITOR_WITH_SELECTION,
            groupId = "extract-refactorings",
            groupPosition = 0,
        ),
        Shortcut(
            id = "extract-method",
            actionId = "ExtractMethod",
            displayName = "Extract Method",
            description = "Extracts the selected code block into a new method, with parameters inferred automatically.",
            category = ShortcutCategory.REFACTORING,
            popularityRank = 54,
            contextType = ContextType.EDITOR_WITH_SELECTION,
            groupId = "extract-refactorings",
            groupPosition = 1,
        ),
        Shortcut(
            id = "extract-field",
            actionId = "IntroduceField",
            displayName = "Extract Field",
            description = "Extracts the selected expression into a class field.",
            category = ShortcutCategory.REFACTORING,
            popularityRank = 56,
            contextType = ContextType.EDITOR_WITH_SELECTION,
        ),
        Shortcut(
            id = "extract-constant",
            actionId = "IntroduceConstant",
            displayName = "Extract Constant",
            description = "Extracts the selected literal or expression into a static constant.",
            category = ShortcutCategory.REFACTORING,
            popularityRank = 57,
            contextType = ContextType.EDITOR_WITH_SELECTION,
        ),
        Shortcut(
            id = "extract-parameter",
            actionId = "IntroduceParameter",
            displayName = "Extract Parameter",
            description = "Extracts the selected expression into a method parameter, updating all call sites.",
            category = ShortcutCategory.REFACTORING,
            popularityRank = 58,
            contextType = ContextType.EDITOR_WITH_SELECTION,
        ),
        Shortcut(
            id = "inline",
            actionId = "Inline",
            displayName = "Inline",
            description = "Inline refactoring — the inverse of Extract. Replaces a variable/method reference with its body.",
            category = ShortcutCategory.REFACTORING,
            popularityRank = 62,
            contextType = ContextType.EDITOR_JAVA,
        ),
        Shortcut(
            id = "change-signature",
            actionId = "ChangeSignature",
            displayName = "Change Method Signature",
            description = "Modifies the method signature (name, parameters, return type) and updates all call sites.",
            category = ShortcutCategory.REFACTORING,
            popularityRank = 63,
            contextType = ContextType.EDITOR_JAVA,
        ),
        Shortcut(
            id = "move-refactoring",
            actionId = "Move",
            displayName = "Move",
            description = "Moves a class or static member to a different package or class.",
            category = ShortcutCategory.REFACTORING,
            popularityRank = 64,
            contextType = ContextType.EDITOR_JAVA,
        ),

        // ════════════════════════════════════════════════════════════════════
        // SEARCH & REPLACE
        // ════════════════════════════════════════════════════════════════════

        Shortcut(
            id = "search-everywhere",
            actionId = "SearchEverywhere",
            displayName = "Search Everywhere",
            description = "Opens a unified search across classes, files, actions, settings, and symbols.",
            category = ShortcutCategory.SEARCH_REPLACE,
            popularityRank = 65,
            contextType = ContextType.ANY,
        ),
        Shortcut(
            id = "find-in-file",
            actionId = "Find",
            displayName = "Find in File",
            description = "Opens the Find toolbar to search for text within the currently active file.",
            category = ShortcutCategory.SEARCH_REPLACE,
            popularityRank = 66,
            contextType = ContextType.EDITOR_ANY_CODE,
        ),
        Shortcut(
            id = "find-in-files",
            actionId = "FindInPath",
            displayName = "Find in Files",
            description = "Opens the Find in Path dialog to search across the entire project or a directory.",
            category = ShortcutCategory.SEARCH_REPLACE,
            popularityRank = 67,
            contextType = ContextType.ANY,
        ),
        Shortcut(
            id = "replace-in-file",
            actionId = "Replace",
            displayName = "Replace in File",
            description = "Opens the Replace toolbar to find and replace text within the current file.",
            category = ShortcutCategory.SEARCH_REPLACE,
            popularityRank = 68,
            contextType = ContextType.EDITOR_ANY_CODE,
        ),
        Shortcut(
            id = "replace-in-files",
            actionId = "ReplaceInPath",
            displayName = "Replace in Files",
            description = "Opens the Replace in Path dialog to replace text across the entire project.",
            category = ShortcutCategory.SEARCH_REPLACE,
            popularityRank = 69,
            contextType = ContextType.ANY,
        ),

        // ════════════════════════════════════════════════════════════════════
        // CODE FOLDING
        // ════════════════════════════════════════════════════════════════════

        Shortcut(
            id = "collapse-block",
            actionId = "CollapseRegion",
            displayName = "Collapse Code Block",
            description = "Collapses the code block at the caret position into a single line.",
            category = ShortcutCategory.CODE_FOLDING,
            popularityRank = 70,
            contextType = ContextType.EDITOR_ANY_CODE,
            groupId = "code-folding",
            groupPosition = 0,
        ),
        Shortcut(
            id = "expand-block",
            actionId = "ExpandRegion",
            displayName = "Expand Code Block",
            description = "Expands a collapsed code block at the caret position.",
            category = ShortcutCategory.CODE_FOLDING,
            popularityRank = 71,
            contextType = ContextType.EDITOR_ANY_CODE,
            groupId = "code-folding",
            groupPosition = 1,
        ),
        Shortcut(
            id = "collapse-all",
            actionId = "CollapseAllRegions",
            displayName = "Collapse All",
            description = "Collapses every foldable region in the current file.",
            category = ShortcutCategory.CODE_FOLDING,
            popularityRank = 72,
            contextType = ContextType.EDITOR_ANY_CODE,
            groupId = "code-folding",
            groupPosition = 2,
        ),
        Shortcut(
            id = "expand-all",
            actionId = "ExpandAllRegions",
            displayName = "Expand All",
            description = "Expands every collapsed region in the current file.",
            category = ShortcutCategory.CODE_FOLDING,
            popularityRank = 73,
            contextType = ContextType.EDITOR_ANY_CODE,
            groupId = "code-folding",
            groupPosition = 3,
        ),

        // ════════════════════════════════════════════════════════════════════
        // BUILD & RUN
        // ════════════════════════════════════════════════════════════════════

        Shortcut(
            id = "build-project",
            actionId = "CompileProject",
            displayName = "Build Project",
            description = "Compiles the entire project, showing errors in the Build tool window.",
            category = ShortcutCategory.BUILD_RUN,
            popularityRank = 75,
            contextType = ContextType.ANY,
        ),
        Shortcut(
            id = "run-context",
            actionId = "RunClass",
            displayName = "Run File / Test at Caret",
            description = "Runs the class or test method at the current caret position.",
            category = ShortcutCategory.BUILD_RUN,
            popularityRank = 76,
            contextType = ContextType.EDITOR_JAVA,
        ),
        Shortcut(
            id = "run-last",
            actionId = "Run",
            displayName = "Run Last Configuration",
            description = "Runs the most recently used run configuration.",
            category = ShortcutCategory.BUILD_RUN,
            popularityRank = 77,
            contextType = ContextType.ANY,
        ),
        Shortcut(
            id = "debug-last",
            actionId = "Debug",
            displayName = "Debug Last Configuration",
            description = "Starts the most recently used configuration in debug mode.",
            category = ShortcutCategory.BUILD_RUN,
            popularityRank = 78,
            contextType = ContextType.ANY,
        ),
        Shortcut(
            id = "stop",
            actionId = "Stop",
            displayName = "Stop",
            description = "Stops the currently running or debugging process.",
            category = ShortcutCategory.BUILD_RUN,
            popularityRank = 79,
            contextType = ContextType.ANY,
        ),

        // ════════════════════════════════════════════════════════════════════
        // DEBUGGING  — canDemonstrate = false for active-session shortcuts
        // ════════════════════════════════════════════════════════════════════

        Shortcut(
            id = "toggle-breakpoint",
            actionId = "ToggleLineBreakpoint",
            displayName = "Toggle Line Breakpoint",
            description = "Sets or removes a line breakpoint on the current line.",
            category = ShortcutCategory.DEBUGGING,
            popularityRank = 80,
            contextType = ContextType.EDITOR_ANY_CODE,
        ),
        Shortcut(
            id = "step-over",
            actionId = "StepOver",
            displayName = "Step Over",
            description = "Executes the next line without stepping inside method calls.",
            category = ShortcutCategory.DEBUGGING,
            popularityRank = 81,
            contextType = ContextType.DEBUGGER_ACTIVE,
            canDemonstrate = false,
            demonstrationNote = "Requires an active debug session paused at a breakpoint. " +
                "The practice project would need to be running in debug mode with execution halted.",
        ),
        Shortcut(
            id = "step-into",
            actionId = "StepInto",
            displayName = "Step Into",
            description = "Steps into the method call on the current line.",
            category = ShortcutCategory.DEBUGGING,
            popularityRank = 82,
            contextType = ContextType.DEBUGGER_ACTIVE,
            canDemonstrate = false,
            demonstrationNote = "Requires an active debug session paused at a breakpoint.",
        ),
        Shortcut(
            id = "step-out",
            actionId = "StepOut",
            displayName = "Step Out",
            description = "Steps out of the current method back to the caller.",
            category = ShortcutCategory.DEBUGGING,
            popularityRank = 83,
            contextType = ContextType.DEBUGGER_ACTIVE,
            canDemonstrate = false,
            demonstrationNote = "Requires an active debug session paused at a breakpoint.",
        ),
        Shortcut(
            id = "resume-program",
            actionId = "Resume",
            displayName = "Resume Program",
            description = "Resumes execution from the current breakpoint until the next one or program end.",
            category = ShortcutCategory.DEBUGGING,
            popularityRank = 84,
            contextType = ContextType.DEBUGGER_ACTIVE,
            canDemonstrate = false,
            demonstrationNote = "Requires an active debug session paused at a breakpoint.",
        ),
        Shortcut(
            id = "evaluate-expression",
            actionId = "EvaluateExpression",
            displayName = "Evaluate Expression",
            description = "Opens the Evaluate Expression dialog to inspect or modify values during a debug session.",
            category = ShortcutCategory.DEBUGGING,
            popularityRank = 85,
            contextType = ContextType.DEBUGGER_ACTIVE,
            canDemonstrate = false,
            demonstrationNote = "Requires an active debug session paused at a breakpoint.",
        ),
        Shortcut(
            id = "run-to-cursor",
            actionId = "RunToCursor",
            displayName = "Run to Cursor",
            description = "Continues execution until the line at the caret, then pauses — a temporary breakpoint.",
            category = ShortcutCategory.DEBUGGING,
            popularityRank = 86,
            contextType = ContextType.DEBUGGER_ACTIVE,
            canDemonstrate = false,
            demonstrationNote = "Requires an active debug session paused at a breakpoint.",
        ),

        // ════════════════════════════════════════════════════════════════════
        // VERSION CONTROL
        // ════════════════════════════════════════════════════════════════════

        Shortcut(
            id = "vcs-commit",
            actionId = "CheckinProject",
            displayName = "Commit",
            description = "Opens the Commit dialog to review, stage, and commit local changes.",
            category = ShortcutCategory.VCS,
            popularityRank = 87,
            contextType = ContextType.VCS_CHANGES,
        ),
        Shortcut(
            id = "vcs-update",
            actionId = "Vcs.UpdateProject",
            displayName = "Update Project (Pull)",
            description = "Updates the project from the remote VCS (equivalent to git pull / svn update).",
            category = ShortcutCategory.VCS,
            popularityRank = 88,
            contextType = ContextType.ANY,
        ),
        Shortcut(
            id = "vcs-push",
            actionId = "Vcs.Push",
            displayName = "Push",
            description = "Opens the Push dialog to push committed changes to the remote repository.",
            category = ShortcutCategory.VCS,
            popularityRank = 89,
            contextType = ContextType.ANY,
        ),
        Shortcut(
            id = "show-diff",
            actionId = "Diff.ShowDiff",
            displayName = "Show Diff",
            description = "Shows the diff of the selected file compared to the last committed revision.",
            category = ShortcutCategory.VCS,
            popularityRank = 90,
            contextType = ContextType.VCS_CHANGES,
        ),
        Shortcut(
            id = "annotate",
            actionId = "Annotate",
            displayName = "Annotate with Git Blame",
            description = "Toggles Git blame annotations in the editor gutter, showing who last changed each line.",
            category = ShortcutCategory.VCS,
            popularityRank = 91,
            contextType = ContextType.EDITOR_ANY_CODE,
        ),

        // ════════════════════════════════════════════════════════════════════
        // TOOL WINDOWS
        // ════════════════════════════════════════════════════════════════════

        Shortcut(
            id = "project-window",
            actionId = "ActivateProjectToolWindow",
            displayName = "Project Tool Window",
            description = "Focuses (or toggles) the Project file tree tool window.",
            category = ShortcutCategory.TOOL_WINDOWS,
            popularityRank = 92,
            contextType = ContextType.ANY,
        ),
        Shortcut(
            id = "find-tool-window",
            actionId = "ActivateFindToolWindow",
            displayName = "Find Tool Window",
            description = "Focuses the Find / Usages results tool window.",
            category = ShortcutCategory.TOOL_WINDOWS,
            popularityRank = 93,
            contextType = ContextType.ANY,
        ),
        Shortcut(
            id = "run-tool-window",
            actionId = "ActivateRunToolWindow",
            displayName = "Run Tool Window",
            description = "Focuses the Run tool window showing the current process output.",
            category = ShortcutCategory.TOOL_WINDOWS,
            popularityRank = 94,
            contextType = ContextType.ANY,
        ),
        Shortcut(
            id = "debug-tool-window",
            actionId = "ActivateDebugToolWindow",
            displayName = "Debug Tool Window",
            description = "Focuses the Debug tool window.",
            category = ShortcutCategory.TOOL_WINDOWS,
            popularityRank = 95,
            contextType = ContextType.ANY,
        ),
        Shortcut(
            id = "terminal-window",
            actionId = "ActivateTerminalToolWindow",
            displayName = "Terminal Tool Window",
            description = "Focuses or opens the embedded terminal tool window.",
            category = ShortcutCategory.TOOL_WINDOWS,
            popularityRank = 96,
            contextType = ContextType.ANY,
        ),
        Shortcut(
            id = "vcs-tool-window",
            actionId = "ActivateVersionControlToolWindow",
            displayName = "Version Control Tool Window",
            description = "Focuses the Version Control / Git tool window (Log, Local Changes, etc.).",
            category = ShortcutCategory.TOOL_WINDOWS,
            popularityRank = 97,
            contextType = ContextType.ANY,
        ),

        // ════════════════════════════════════════════════════════════════════
        // WINDOW MANAGEMENT
        // ════════════════════════════════════════════════════════════════════

        Shortcut(
            id = "close-active-tab",
            actionId = "CloseContent",
            displayName = "Close Active Tab",
            description = "Closes the currently focused editor tab.",
            category = ShortcutCategory.WINDOW_MANAGEMENT,
            popularityRank = 98,
            contextType = ContextType.MULTIPLE_TABS_OPEN,
        ),
        Shortcut(
            id = "split-vertical",
            actionId = "SplitVertically",
            displayName = "Split Editor Vertically",
            description = "Splits the editor into two vertical panes, placing the current file in both.",
            category = ShortcutCategory.WINDOW_MANAGEMENT,
            popularityRank = 99,
            contextType = ContextType.EDITOR_ANY_CODE,
        ),
        Shortcut(
            id = "split-horizontal",
            actionId = "SplitHorizontally",
            displayName = "Split Editor Horizontally",
            description = "Splits the editor into two horizontal panes (one above, one below).",
            category = ShortcutCategory.WINDOW_MANAGEMENT,
            popularityRank = 100,
            contextType = ContextType.EDITOR_ANY_CODE,
        ),
        Shortcut(
            id = "hide-all-windows",
            actionId = "HideAllWindows",
            displayName = "Hide / Restore All Tool Windows",
            description = "Hides all tool windows so you can focus on the editor; press again to restore them.",
            category = ShortcutCategory.WINDOW_MANAGEMENT,
            popularityRank = 101,
            contextType = ContextType.ANY,
        ),

        // ── Shortcuts that CANNOT be demonstrated interactively ───────────────

        Shortcut(
            id = "toggle-full-screen",
            actionId = "ToggleFullScreen",
            displayName = "Toggle Full Screen",
            description = "Switches the IDE between full-screen and windowed mode.",
            category = ShortcutCategory.WINDOW_MANAGEMENT,
            popularityRank = 150,
            contextType = ContextType.ANY,
            canDemonstrate = false,
            demonstrationNote = "Toggling full-screen hides the ShortcutSensei tool window, making it " +
                "impossible to see the practice prompt or the Reveal button.",
        ),
        Shortcut(
            id = "distraction-free-mode",
            actionId = "ToggleDistractionFreeMode",
            displayName = "Distraction Free Mode",
            description = "Enters/exits distraction-free mode, hiding all tool windows, menus, and the status bar.",
            category = ShortcutCategory.WINDOW_MANAGEMENT,
            popularityRank = 151,
            contextType = ContextType.ANY,
            canDemonstrate = false,
            demonstrationNote = "This mode hides all UI panels including the ShortcutSensei practice window.",
        ),
        Shortcut(
            id = "presentation-mode",
            actionId = "TogglePresentationMode",
            displayName = "Presentation Mode",
            description = "Enters/exits presentation mode with enlarged fonts and a simplified UI for presenting code on a projector.",
            category = ShortcutCategory.WINDOW_MANAGEMENT,
            popularityRank = 152,
            contextType = ContextType.ANY,
            canDemonstrate = false,
            demonstrationNote = "Presentation mode enlarges the UI and hides tool windows, disrupting the practice session.",
        ),
        Shortcut(
            id = "exit-application",
            actionId = "Exit",
            displayName = "Exit (Close IDE)",
            description = "Closes IntelliJ IDEA completely.",
            category = ShortcutCategory.WINDOW_MANAGEMENT,
            popularityRank = 200,
            contextType = ContextType.ANY,
            canDemonstrate = false,
            demonstrationNote = "Executing this shortcut would close the IDE and terminate the practice session entirely.",
        ),
        Shortcut(
            id = "invalidate-caches",
            actionId = "InvalidateCaches",
            displayName = "Invalidate Caches and Restart",
            description = "Clears all IDE index caches and restarts IntelliJ IDEA.",
            category = ShortcutCategory.FILE_MANAGEMENT,
            popularityRank = 201,
            contextType = ContextType.ANY,
            canDemonstrate = false,
            demonstrationNote = "This action restarts the IDE, which would terminate the practice session.",
        ),
        Shortcut(
            id = "start-macro-recording",
            actionId = "StartMacroRecording",
            displayName = "Start Macro Recording",
            description = "Starts recording all subsequent actions as a replayable macro.",
            category = ShortcutCategory.EDITING,
            popularityRank = 180,
            contextType = ContextType.ANY,
            canDemonstrate = false,
            demonstrationNote = "Macro recording captures all key events, which would interfere with " +
                "ShortcutSensei's own key-capture mechanism.",
        ),
        Shortcut(
            id = "collect-coverage",
            actionId = "Coverage",
            displayName = "Run with Coverage",
            description = "Runs the current configuration with code coverage instrumentation enabled.",
            category = ShortcutCategory.BUILD_RUN,
            popularityRank = 160,
            contextType = ContextType.ANY,
            canDemonstrate = false,
            demonstrationNote = "Coverage requires a real run configuration targeting compilable source code " +
                "and a JVM agent; cannot be set up within the sandboxed practice project.",
        ),
    )
}
